### ISSUE TITLE
DevOps가 무엇일까

### ISSUE THREAD

**Issue by seulkibae** [seulkibae/ModuleNaver3#2]
Devlopment + Operations?

**Comment by seulkibae** [comment]
Devlopment + Operations?

**Comment by portable93** [comment]
먹는건가

**Comment by kimins10** [comment]
새로운 기술을 받아들여서 개발하고 안정적으로 운영하는 것?

**Comment by jinsu89** [comment]
개발, 배포, 운영, 관리

**Comment by portable93** [comment]
새로운 변화 또는 기술 코드 작성 + 안정적인 운영 + 개발 문화

**Comment by sirmd** [comment]
DevOps = 개뱔 / 운영 / 배포를 통합적으로 관리하는 기술적인 용어
DevOps 엔지니어 = DevOps를 운영 하는 사람
DevSecOps = 개발 / 운영 / 배포 시 보안까지 확인하고 통합적으로 관리하는 기술적 용어
DevSecOps 에서는 보안팀까지 참여하는 것이 중요
DevOps와 DevSecOps 모두 참여하는 사람의 협업과 기업 또는 팀과 부서 문화가 중요하고
마지막으로 경영진의 의지가 중요함
